import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Gabarito } from 'next/font/google';
import ClientWrapper from './components/ClientWrapper';
import SessionWrapper from './SessionWrapper';

const prompt = Gabarito({
  weight: '400',
  subsets: ['latin']
})

export const metadata = {
  title: "Patinha do Bem",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className={prompt.className}>
      <body>
        <SessionWrapper>
          <ClientWrapper>
            {children}
          </ClientWrapper>
        </SessionWrapper>
      </body>
    </html>
  );
}
